# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 13:18
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from users.models import RoleType


def add_default_roles(*args, **kwargs):
    for role_type in settings.DEFAULT_ROLES:
        RoleType.objects.get_or_create(
            name=role_type
        )


def revert_add_default_roles(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_roles)
    ]
